/* ===== ACE BANK V2 — ACCOUNT OPENING ===== */
function renderAccount(c) {
    App.formStep = 1;
    c.innerHTML = `<div class="ao-container">
  <div class="ao-sidebar">
    <div class="card"><div class="card-title"><span class="material-symbols-outlined">verified</span>Why ACE Bank?</div>
      <ul style="display:flex;flex-direction:column;gap:8px;font-size:13px;color:var(--text-muted)">${['Zero min balance (Regular)', 'Instant account opening', '5X reward points on investments', 'Free NEFT/RTGS/IMPS forever', 'Dedicated RM (Premium)'].map(t => `<li style="display:flex;gap:8px;align-items:center"><span class="material-symbols-outlined" style="font-size:16px;color:var(--ace-green)">check_circle</span>${t}</li>`).join('')}</ul></div>
    <div class="card"><div class="card-title"><span class="material-symbols-outlined">gpp_good</span>Eligibility</div>
      <ul style="display:flex;flex-direction:column;gap:6px;font-size:12px;color:var(--text-muted)"><li><strong>Age:</strong> 18+ years</li><li><strong>KYC:</strong> Valid PAN & Aadhaar</li><li><strong>Residency:</strong> Indian Resident</li></ul></div>
    <div class="card"><div class="card-title"><span class="material-symbols-outlined">payments</span>Min Deposit</div>
      <table style="font-size:12px;width:100%"><tr style="font-weight:600"><td>Regular</td><td>₹0</td><td>Daily banking</td></tr><tr style="font-weight:600"><td>Premium</td><td>₹10,000</td><td>Wealth + perks</td></tr><tr style="font-weight:600"><td>Current</td><td>₹5,000</td><td>Business</td></tr></table></div>
    <div class="card" style="text-align:center"><span class="material-symbols-outlined" style="font-size:20px;color:var(--ace-green)">lock</span><div style="font-size:11px;color:var(--text-faint);margin-top:4px">256-bit SSL Encrypted</div></div>
  </div>
  <div class="ao-panel">
    <div class="ao-progress"><div class="ao-progress-text"><strong id="aoStepName">Step 1 — Personal Details</strong><span id="aoStepNum">1 of 7</span></div><div class="progress-bar"><div class="progress-fill" id="aoBar" style="width:14.28%;background:var(--ace-blue)"></div></div><div class="ao-dots" id="aoDots">${[1, 2, 3, 4, 5, 6, 7].map(i => `<div class="ao-dot ${i === 1 ? 'current' : ''}" data-s="${i}"></div>`).join('')}</div></div>
    <form id="aoForm" onsubmit="event.preventDefault();submitAO()">
    <!-- STEP 1 -->
    <div class="form-step active" id="aoS1">
      <div class="step-title"><span class="material-symbols-outlined">person</span>Personal Details</div>
      <div class="form-grid form-grid-3"><div class="form-group"><label class="form-label">First Name *</label><input class="form-control" name="firstName" required></div><div class="form-group"><label class="form-label">Middle Name</label><input class="form-control" name="middleName"></div><div class="form-group"><label class="form-label">Last Name *</label><input class="form-control" name="lastName" required></div></div>
      <div class="form-grid form-grid-2"><div class="form-group"><label class="form-label">Date of Birth *</label><input type="date" class="form-control" name="dob" required onchange="validateAge(this)"><div class="form-error" id="ageErr">Must be 18+ years old</div></div><div class="form-group"><label class="form-label">Gender *</label><div class="radio-pills" id="genderPills"><div class="radio-pill" onclick="selectPill(this,'gender')">Male</div><div class="radio-pill" onclick="selectPill(this,'gender')">Female</div><div class="radio-pill" onclick="selectPill(this,'gender')">Non-Binary</div></div><input type="hidden" name="gender" required></div></div>
      <div class="form-grid form-grid-2"><div class="form-group"><label class="form-label">Marital Status *</label><select class="form-control" name="maritalStatus" required><option value="">Select</option><option>Single</option><option>Married</option><option>Divorced</option><option>Widowed</option></select></div><div class="form-group"><label class="form-label">Nationality</label><input class="form-control" name="nationality" value="Indian"></div></div>
      <div class="form-grid form-grid-2"><div class="form-group"><label class="form-label">Father's Name *</label><input class="form-control" name="fatherName" required></div><div class="form-group"><label class="form-label">Mother's Name *</label><input class="form-control" name="motherName" required></div></div>
      <div class="form-grid form-grid-2"><div class="form-group"><label class="form-label">Place of Birth</label><input class="form-control" name="pob"></div></div>
    </div>
    <!-- STEP 2 -->
    <div class="form-step" id="aoS2">
      <div class="step-title"><span class="material-symbols-outlined">call</span>Contact Information</div>
      <div class="form-grid form-grid-2"><div class="form-group"><label class="form-label">Mobile Number *</label><div style="display:flex;gap:8px"><span style="padding:12px;background:var(--bg-body);border-radius:var(--r-sm);font-size:13px;font-weight:600;white-space:nowrap">🇮🇳 +91</span><input class="form-control" name="mobile" placeholder="10-digit" maxlength="10" required style="flex:1"><button type="button" class="btn btn-secondary btn-sm" id="otpBtn" onclick="sendOTP()">Get OTP</button></div></div><div class="form-group"><label class="form-label">Email *</label><input type="email" class="form-control" name="email" required></div></div>
      <div id="otpSection" style="display:none;margin-top:16px"><label class="form-label" style="margin-bottom:8px">Enter OTP</label><div class="otp-boxes">${[1, 2, 3, 4, 5, 6].map(i => `<input class="otp-box" maxlength="1" oninput="otpAdvance(this,${i})" onkeydown="otpBack(event,${i})" id="otp${i}">`).join('')}</div><div id="otpStatus" style="margin-top:8px"></div></div>
      <div class="form-grid form-grid-2" style="margin-top:16px"><div class="form-group"><label class="form-label">Alternate Mobile</label><input class="form-control" name="altMobile" maxlength="10"></div><div class="form-group"><label class="custom-check" style="margin-top:28px"><input type="checkbox" name="whatsapp"><div class="check-box"></div>Use this number for WhatsApp alerts</label></div></div>
    </div>
    <!-- STEP 3 -->
    <div class="form-step" id="aoS3">
      <div class="step-title"><span class="material-symbols-outlined">badge</span>KYC Details</div>
      <div class="form-grid form-grid-2"><div class="form-group"><label class="form-label">PAN Number *</label><input class="form-control" name="pan" maxlength="10" required style="text-transform:uppercase" oninput="this.value=this.value.toUpperCase();validatePAN(this)"><div class="form-error" id="panErr">Invalid PAN format (e.g. ABCDE1234F)</div><div class="form-success" id="panOk" style="display:none"><span class="material-symbols-outlined" style="font-size:14px">check_circle</span>Valid PAN</div></div><div class="form-group"><label class="form-label">Aadhaar Number *</label><input class="form-control" name="aadhaar" maxlength="14" required oninput="fmtAadhaar(this)"></div></div>
      <div class="form-grid form-grid-2"><div class="form-group"><label class="form-label">Voter ID</label><input class="form-control" name="voterId"></div><div class="form-group"><label class="form-label">Passport Number</label><input class="form-control" name="passport" oninput="togglePassport(this.value)"></div></div>
      <div id="passportExtra" style="display:none;margin-top:16px"><div class="form-grid form-grid-3"><div class="form-group"><label class="form-label">Issue Date</label><input type="date" class="form-control" name="passIssue"></div><div class="form-group"><label class="form-label">Expiry Date</label><input type="date" class="form-control" name="passExpiry"></div><div class="form-group"><label class="form-label">Place of Issue</label><input class="form-control" name="passPlace"></div></div></div>
      <div class="form-grid form-grid-2" style="margin-top:16px">${['PAN Card', 'Aadhaar Card', 'Photograph', 'Signature'].map((l, i) => `<div class="form-group"><label class="form-label">${l}</label><div class="file-upload" onclick="this.querySelector('input').click()"><input type="file" accept="image/*" onchange="previewUpload(this)"><span class="material-symbols-outlined">${['description', 'badge', 'photo_camera', 'draw'][i]}</span><p>${l}</p><span class="hint">JPG/PNG${i >= 2 ? ', max ' + (i === 3 ? '200KB' : '500KB') : ', max 2MB'}</span><img class="preview"></div></div>`).join('')}</div>
    </div>
    <!-- STEP 4 -->
    <div class="form-step" id="aoS4">
      <div class="step-title"><span class="material-symbols-outlined">home</span>Address Details</div>
      <div class="form-group"><label class="form-label">Address Line 1 *</label><input class="form-control" name="addr1" required></div>
      <div class="form-group"><label class="form-label">Address Line 2</label><input class="form-control" name="addr2"></div>
      <div class="form-grid form-grid-3"><div class="form-group"><label class="form-label">PIN Code *</label><input class="form-control" name="pin" maxlength="6" required oninput="lookupPIN(this.value)"></div><div class="form-group"><label class="form-label">City *</label><input class="form-control" name="city" id="aoCity" required></div><div class="form-group"><label class="form-label">State *</label><select class="form-control" name="state" id="aoState" required><option value="">Select</option>${states.map(s => `<option>${s}</option>`).join('')}</select></div></div>
      <div class="form-group"><label class="form-label">Country</label><input class="form-control" name="country" value="India"></div>
      <label class="custom-check" style="margin-top:8px"><input type="checkbox" checked onchange="togglePermAddr(this.checked)"><div class="check-box"></div>Permanent address is same as current address</label>
      <div id="permAddrSect" style="display:none;margin-top:16px;max-height:0;overflow:hidden;transition:max-height .4s ease"><div class="form-group"><label class="form-label">Permanent Address *</label><input class="form-control" name="permAddr"></div><div class="form-grid form-grid-2"><div class="form-group"><label class="form-label">City *</label><input class="form-control" name="permCity"></div><div class="form-group"><label class="form-label">State *</label><select class="form-control" name="permState"><option value="">Select</option>${states.map(s => `<option>${s}</option>`).join('')}</select></div></div></div>
    </div>
    <!-- STEP 5 -->
    <div class="form-step" id="aoS5">
      <div class="step-title"><span class="material-symbols-outlined">work</span>Financial Information</div>
      <div class="form-group"><label class="form-label">Occupation *</label><div class="radio-pills">${['Salaried', 'Self-Employed', 'Business', 'Student', 'Retired', 'Homemaker'].map(o => `<div class="radio-pill" onclick="selectPill(this,'occupation');toggleOccFields('${o}')">${o}</div>`).join('')}</div><input type="hidden" name="occupation" required></div>
      <div id="salFields" style="display:none;margin-top:16px"><div class="form-grid form-grid-3"><div class="form-group"><label class="form-label">Employer Name *</label><input class="form-control" name="employer" id="empField"></div><div class="form-group"><label class="form-label">Employee ID</label><input class="form-control" name="empId"></div><div class="form-group"><label class="form-label">Work Email</label><input type="email" class="form-control" name="workEmail"></div></div></div>
      <div id="bizFields" style="display:none;margin-top:16px"><div class="form-grid form-grid-3"><div class="form-group"><label class="form-label">Business Name *</label><input class="form-control" name="bizName" id="bizField"></div><div class="form-group"><label class="form-label">GSTIN</label><input class="form-control" name="gstin"></div><div class="form-group"><label class="form-label">Business Type</label><select class="form-control" name="bizType"><option value="">Select</option><option>Proprietorship</option><option>Partnership</option><option>Pvt Ltd</option><option>LLP</option></select></div></div></div>
      <div id="stuFields" style="display:none;margin-top:16px"><div class="form-grid form-grid-2"><div class="form-group"><label class="form-label">Institution Name</label><input class="form-control" name="institution"></div><div class="form-group"><label class="form-label">Course</label><input class="form-control" name="course"></div></div></div>
      <div class="form-group" style="margin-top:16px"><label class="form-label">Annual Income *</label><div class="radio-pills">${['< ₹2L', '₹2-5L', '₹5-10L', '₹10-25L', '₹25-50L', '₹50L+'].map(i => `<div class="radio-pill" onclick="selectPill(this,'income')">${i}</div>`).join('')}</div><input type="hidden" name="income" required></div>
      <div class="form-group" style="margin-top:16px"><label class="form-label">Source of Funds *</label><div style="display:flex;gap:8px;flex-wrap:wrap">${['Salary', 'Business', 'Investments', 'Inheritance', 'Rental Income', 'Gifts', 'Other'].map(s => `<div class="chip chip-primary" onclick="this.classList.toggle('active')">${s}</div>`).join('')}</div></div>
    </div>
    <!-- STEP 6 -->
    <div class="form-step" id="aoS6">
      <div class="step-title"><span class="material-symbols-outlined">family_restroom</span>Nominee Details</div>
      <div class="form-grid form-grid-2"><div class="form-group"><label class="form-label">Nominee Full Name *</label><input class="form-control" name="nomName" required></div><div class="form-group"><label class="form-label">Relationship *</label><select class="form-control" name="nomRel" required><option value="">Select</option>${['Spouse', 'Father', 'Mother', 'Son', 'Daughter', 'Brother', 'Sister', 'Other'].map(r => `<option>${r}</option>`).join('')}</select></div></div>
      <div class="form-grid form-grid-2"><div class="form-group"><label class="form-label">Nominee DOB *</label><input type="date" class="form-control" name="nomDob" required onchange="checkNomAge(this.value)"></div><div class="form-group"><label class="form-label">Nominee Aadhaar</label><input class="form-control" name="nomAadhaar" maxlength="14" oninput="fmtAadhaar(this)"></div></div>
      <div id="nomAgeBadge" style="margin-top:8px;display:none"></div>
      <div id="guardianSect" style="display:none;margin-top:16px;padding:20px;background:#fffbeb;border-radius:var(--r-md);border-left:4px solid var(--ace-orange)"><h4 style="font-size:14px;margin-bottom:16px;color:var(--ace-red)">👶 Minor Nominee — Guardian Required</h4><div class="form-grid form-grid-2"><div class="form-group"><label class="form-label">Guardian Name *</label><input class="form-control" name="guardName"></div><div class="form-group"><label class="form-label">Guardian Relationship *</label><select class="form-control" name="guardRel"><option value="">Select</option><option>Father</option><option>Mother</option><option>Legal Guardian</option></select></div><div class="form-group"><label class="form-label">Guardian Mobile *</label><input class="form-control" name="guardMob" maxlength="10"></div><div class="form-group"><label class="form-label">Guardian Aadhaar</label><input class="form-control" name="guardAadhaar" maxlength="14"></div></div></div>
      <div class="form-grid form-grid-2" style="margin-top:16px"><div class="form-group"><label class="form-label">Allocation %</label><input class="form-control" name="nomPct" type="number" value="100" max="100"></div></div>
    </div>
    <!-- STEP 7 -->
    <div class="form-step" id="aoS7">
      <div class="step-title"><span class="material-symbols-outlined">tune</span>Account Preferences</div>
      <label class="form-label" style="margin-bottom:12px">Account Type *</label>
      <div class="acc-type-cards">${[{ t: 'Regular Savings', p: '₹0 min balance', f: ['Basic debit card', '1X rewards', 'Standard features'], border: '', badge: '' }, { t: 'Premium Savings', p: '₹10,000 min balance', f: ['VISA Platinum', '5X rewards', 'Lounge access', 'Priority support'], border: 'var(--ace-gold)', badge: 'RECOMMENDED' }, { t: 'Current Account', p: '₹5,000 min balance', f: ['Business cheques', 'OD facility', 'GST invoicing', 'Multi-user access'], border: '', badge: '' }].map((a, i) => `<div class="acc-type-card ${i === 1 ? 'selected' : ''}" onclick="selectAccType(this,${i})" ${i === 1 ? 'style="border-color:var(--ace-gold)"' : ''}>${a.badge ? `<div class="rec">${a.badge}</div>` : ''}<h4 style="font-size:16px;font-weight:700;margin-bottom:4px">${a.t}</h4><p style="font-size:12px;color:var(--text-faint);margin-bottom:12px">${a.p}</p><ul style="font-size:12px;color:var(--text-muted)">${a.f.map(f => `<li style="margin-bottom:6px;display:flex;gap:6px;align-items:center"><span class="material-symbols-outlined" style="font-size:14px;color:var(--ace-green)">check</span>${f}</li>`).join('')}</ul></div>`).join('')}</div>
      <input type="hidden" name="accType" id="accTypeIn" value="Premium Savings">
      <div class="form-grid form-grid-2" style="margin-top:20px"><div class="form-group"><label class="form-label">Preferred Branch</label><select class="form-control" name="branch">${Object.entries(branches).flatMap(([city, bs]) => bs.map(b => `<option>${city} — ${b}</option>`)).join('')}</select></div><div class="form-group"><label class="form-label">Preferred Language</label><select class="form-control" name="language"><option>English</option><option>Hindi</option><option>Tamil</option><option>Telugu</option><option>Bengali</option></select></div></div>
      <div style="margin-top:20px;display:flex;flex-direction:column;gap:12px">${['Visa Debit Card', 'Cheque Book', 'Internet Banking', 'Mobile Banking', 'SMS Alerts', 'Email Statements'].map((l, i) => `<label class="custom-check"><input type="checkbox" name="pref_${l.replace(/ /g, '_')}" ${i >= 2 ? 'checked' : ''}><div class="check-box"></div>${l}</label>`).join('')}</div>
      <div style="margin-top:24px;padding:20px;background:#fffbeb;border-radius:var(--r-md);border:1px solid #fde68a"><h4 style="font-size:14px;margin-bottom:12px">⚠ Mandatory Declarations</h4><label class="custom-check" style="margin-bottom:12px"><input type="checkbox" name="fatca" required><div class="check-box"></div>I confirm I am not a US person for tax purposes (FATCA Declaration)</label><label class="custom-check" style="margin-bottom:12px"><input type="checkbox" name="pep"><div class="check-box"></div>I declare I am not a Politically Exposed Person (PEP)</label><label class="custom-check"><input type="checkbox" name="tnc" required><div class="check-box"></div>I agree to the Terms & Conditions of ACE Bank</label></div>
    </div>
    <!-- STEP 8 SUMMARY -->
    <div class="form-step" id="aoS8"><div id="aoSummary"></div></div>
    <div class="form-nav"><button type="button" class="btn btn-secondary" id="aoPrev" onclick="aoNav(-1)" style="display:none"><span class="material-symbols-outlined">arrow_back</span>Previous</button><div style="flex:1"></div><button type="button" class="btn btn-primary" id="aoNext" onclick="aoNav(1)">Next<span class="material-symbols-outlined">arrow_forward</span></button><button type="submit" class="btn btn-success btn-lg" id="aoSubmit" style="display:none"><span class="material-symbols-outlined">check_circle</span>Confirm & Submit</button></div>
    </form>
  </div></div>`;
}

const stepNames = ['Personal Details', 'Contact Info', 'KYC Details', 'Address', 'Financial Info', 'Nominee', 'Preferences', 'Review & Confirm'];
function selectPill(el, name) { el.parentElement.querySelectorAll('.radio-pill').forEach(p => p.classList.remove('selected')); el.classList.add('selected'); const inp = document.querySelector(`[name="${name}"]`); if (inp) inp.value = el.textContent }
function selectAccType(el, idx) { $$('.acc-type-card').forEach(c => c.classList.remove('selected')); el.classList.add('selected'); $('#accTypeIn').value = ['Regular Savings', 'Premium Savings', 'Current Account'][idx] }
function validateAge(el) { const age = calculateAge(el.value); if (age < 18) { el.classList.add('error'); $('#ageErr').style.display = 'block' } else { el.classList.remove('error'); $('#ageErr').style.display = 'none' } }
function sendOTP() { $('#otpSection').style.display = 'block'; const btn = $('#otpBtn'); let t = 59; btn.disabled = true; btn.textContent = `Resend (${t}s)`; const iv = setInterval(() => { t--; btn.textContent = `Resend (${t}s)`; if (t <= 0) { clearInterval(iv); btn.disabled = false; btn.textContent = 'Resend OTP' } }, 1000); showToast('OTP sent to your mobile', 'info') }
function otpAdvance(el, idx) { if (el.value.length === 1 && idx < 6) $('#otp' + (idx + 1)).focus(); if (idx === 6 && el.value) { const code = [1, 2, 3, 4, 5, 6].map(i => $('#otp' + i).value).join(''); if (code === '123456') { $('#otpStatus').innerHTML = '<span class="form-success"><span class="material-symbols-outlined" style="font-size:14px">check_circle</span>Mobile Verified</span>'; showToast('Mobile verified!', 'success') } else { $$('.otp-box').forEach(b => { b.style.animation = 'shake .4s ease'; b.style.borderColor = 'var(--ace-red)'; setTimeout(() => { b.style.animation = ''; b.style.borderColor = '' }, 500) }); $('#otpStatus').innerHTML = '<span style="color:var(--ace-red);font-size:12px">Invalid OTP. Try 123456</span>' } } }
function otpBack(e, idx) { if (e.key === 'Backspace' && !e.target.value && idx > 1) $('#otp' + (idx - 1)).focus() }
function validatePAN(el) { const v = el.value; const ok = /^[A-Z]{5}[0-9]{4}[A-Z]{1}$/.test(v); $('#panErr').style.display = v.length === 10 && !ok ? 'block' : 'none'; $('#panOk').style.display = ok ? 'flex' : 'none'; if (v.length === 10 && !ok) el.classList.add('error'); else el.classList.remove('error') }
function fmtAadhaar(el) { let v = el.value.replace(/\D/g, ''); let m = v.match(/^(\d{0,4})(\d{0,4})(\d{0,4})$/); if (m) el.value = !m[2] ? m[1] : m[1] + '-' + m[2] + (m[3] ? '-' + m[3] : '') }
function togglePassport(v) { $('#passportExtra').style.display = v ? 'block' : 'none' }
function previewUpload(input) { if (input.files[0]) { const r = new FileReader(); r.onload = e => { const p = input.parentElement; p.querySelector('.preview').src = e.target.result; p.classList.add('uploaded') }; r.readAsDataURL(input.files[0]) } }
function lookupPIN(v) { if (v.length === 6 && pinDB[v]) { $('#aoCity').value = pinDB[v].city; $('#aoState').value = pinDB[v].state; showToast('Auto-filled: ' + pinDB[v].city + ', ' + pinDB[v].state, 'info') } }
function togglePermAddr(checked) { const s = $('#permAddrSect'); s.style.display = checked ? 'none' : 'block'; s.style.maxHeight = checked ? '0' : '500px' }
function toggleOccFields(occ) { $('#salFields').style.display = occ === 'Salaried' ? 'block' : 'none'; $('#bizFields').style.display = occ === 'Business' ? 'block' : 'none'; $('#stuFields').style.display = occ === 'Student' ? 'block' : 'none' }
function checkNomAge(dob) { const age = calculateAge(dob); $('#nomAgeBadge').style.display = 'inline-block'; $('#nomAgeBadge').innerHTML = `<span class="badge" style="background:${age < 18 ? 'var(--ace-red-light)' : 'var(--ace-green-light)'};color:${age < 18 ? '#991b1b' : '#065f46'}">Age: ${age} years</span>`; $('#guardianSect').style.display = age < 18 ? 'block' : 'none' }

function aoNav(dir) {
    if (dir === 1 && App.formStep <= 7) {
        const step = $('#aoS' + App.formStep); const inputs = step.querySelectorAll('[required]'); let ok = true; inputs.forEach(i => { if (!i.value) { i.classList.add('error'); ok = false } else i.classList.remove('error') }); if (!ok) { showToast('Please fill all required fields', 'error'); return }
        if (App.formStep === 7) buildAOSummary()
    }
    const next = App.formStep + dir; if (next >= 1 && next <= 8) { App.formStep = next; updateAOUI() }
}

function updateAOUI() { $$('.form-step').forEach(s => s.classList.remove('active')); $('#aoS' + App.formStep).classList.add('active'); $('#aoStepName').textContent = App.formStep <= 7 ? `Step ${App.formStep} — ${stepNames[App.formStep - 1]}` : 'Review & Confirm'; $('#aoStepNum').textContent = App.formStep <= 7 ? `${App.formStep} of 7` : 'Final'; $('#aoBar').style.width = (Math.min(App.formStep, 7) / 7 * 100) + '%'; $$('.ao-dot').forEach((d, i) => { d.className = 'ao-dot'; if (i < App.formStep - 1) d.classList.add('done'); if (i === App.formStep - 1) d.classList.add('current') }); $('#aoPrev').style.display = App.formStep === 1 ? 'none' : 'flex'; $('#aoNext').style.display = App.formStep >= 8 ? 'none' : 'flex'; $('#aoSubmit').style.display = App.formStep === 8 ? 'flex' : 'none' }

function buildAOSummary() {
    const fd = new FormData($('#aoForm')); const fields = [['First Name', 'firstName'], ['Last Name', 'lastName'], ['DOB', 'dob'], ['Gender', 'gender'], ['Mobile', 'mobile'], ['Email', 'email'], ['PAN', 'pan'], ['City', 'city'], ['State', 'state'], ['Occupation', 'occupation'], ['Income', 'income'], ['Account Type', 'accType'], ['Nominee', 'nomName'], ['Branch', 'branch']]; let html = '<div class="step-title"><span class="material-symbols-outlined">fact_check</span>Review & Confirm</div><p style="color:var(--text-muted);margin-bottom:24px">Please review your details carefully before submitting.</p>';
    fields.forEach(([l, k]) => { const v = fd.get(k) || '—'; html += `<div class="profile-row"><span class="label">${l}</span><span class="value">${v}</span></div>` });
    html += `<div style="margin-top:24px;padding:20px;background:var(--bg-body);border-radius:var(--r-md)"><div style="display:flex;justify-content:space-between;margin-bottom:8px;font-size:13px"><span>Account Type</span><strong>${fd.get('accType') || 'Premium Savings'}</strong></div><div style="display:flex;justify-content:space-between;margin-bottom:8px;font-size:13px"><span>Min. Deposit</span><strong>₹10,000</strong></div><div style="display:flex;justify-content:space-between;font-size:15px;font-weight:800;padding-top:8px;border-top:1px solid var(--border)"><span>Total to Pay</span><span style="color:var(--ace-blue)">₹10,000</span></div></div><div style="margin-top:16px;padding:12px;background:var(--ace-blue-light);border-radius:var(--r-sm);text-align:center;font-size:13px"><span class="material-symbols-outlined" style="font-size:16px;vertical-align:middle;color:var(--ace-blue)">schedule</span> Account opens in 24–48 hours after verification</div>`;
    $('#aoSummary').innerHTML = html
}

function submitAO() { const p = $('.ao-panel'); p.innerHTML = '<div class="success-screen"><div class="success-check"><span class="material-symbols-outlined">check_circle</span></div><h2 style="font-size:28px;font-weight:800;margin-bottom:8px">🎉 Application Submitted!</h2><p style="color:var(--text-muted)">Your account will be activated within 24-48 hours.<br>Video KYC link sent to your mobile.</p><div class="success-ref">ACE-2025-' + Math.random().toString(36).substring(2, 10).toUpperCase() + '</div><br><div style="display:flex;gap:12px;justify-content:center"><button class="btn btn-secondary" onclick="showToast(\'Tracking feature coming soon\',\'info\')"><span class="material-symbols-outlined">track_changes</span>Track Application</button><button class="btn btn-primary" onclick="navigate(\'dashboard\')"><span class="material-symbols-outlined">dashboard</span>Go to Dashboard</button></div></div>'; launchConfetti(); showToast('Application submitted successfully!', 'success') }
